# .prettierrc or .prettierrc.yaml
trailingComma: 'es5'
tabWidth: 4
semi: true
singleQuote: true
printWidth: 100
useTabs: true
overrides:
  - files: ['**/*.yaml', '**/*.yml']
    options:
      tabWidth: 2
      useTabs: false
